app_name: "My Graph RAG App"
api_v1_str: "/api/v1"

# --- LLM Models ---
llm_ingestion_model_name: "gpt-4o"
llm_query_response_model_name: "gpt-4o-mini"

retrieval_pipeline:
  # Stage 1: How many chunks to fetch for initial context
  context_chunks_for_expansion: 2

  # Stage 2: How many chunks to retrieve in the main search
  # This should be larger to accommodate results from multiple queries
  main_search_top_k: 15

  # This is when multiple files are selected, 3 chunks per file are retrieved
  per_file_chunk_limit: 3

  # Stage 3: Query expansion settings
  query_expansion:
    enabled: true
    llm_model_name: "gpt-4o-mini"
    # How many alternative queries to generate
    num_expansions: 3

  # Stage 4: Re-ranking settings
  reranking:
    enabled: true
    model_repo: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    # After re-ranking the main_search_top_k results, how many to keep for single document
    final_top_n: 3

# --- Embedding Model (Hugging Face) ---
# This repo will be used by Weaviate's text2vec-transformers module.
# Ensure the model selected here matches the one in the docker-compose service if pre-loading.
# Example: "sentence-transformers/all-mpnet-base-v2"
embedding_model_repo: "sentence-transformers/multi-qa-mpnet-base-cos-v1"
embedding_dimension: 768 # Must match the dimension of the chosen model

# --- File and Data Storage ---
schema_file_path: "schema.yaml"
prompts_file_path: "prompts.yaml"
# Directory for storing copies of uploaded original files
file_storage_path: "data/uploaded_files"
# Path for the SQLite database that tracks file metadata
sqlite_db_path: "data/file_metadata.db"
# Path for log files
log_file_path: "logs/graph_rag_app.log"
log_retention_days: 7

# --- Weaviate Configuration ---
# Name of the data collection (class) inside Weaviate
weaviate_class_name: "TextChunk"

# --- Retrieval Parameters ---
semantic_search_top_k: 3 # Number of text chunks to retrieve
entity_info_hop_depth: 1 # How many hops to explore around entities found in chunks

# --- Graph Explorer Defaults ---
default_full_graph_node_limit: 100
default_full_graph_edge_limit: 150