app_name: "My Graph RAG App"
api_v1_str: "/api/v1"

llm_ingestion_model_name: "gpt-4o"
llm_query_ner_model_name: "gpt-4o-mini"
llm_query_intent_model_name: "gpt-4o-mini"
llm_query_response_model_name: "gpt-4o-mini"
llm_embedding_model_name: "text-embedding-3-small"
embedding_dimension: 1536 # Optional: can be derived or set explicitly

schema_file_path: "schema.yaml"
prompts_file_path: "prompts.yaml"

faiss_index_path: "data/vector_store/graph_rag_chunks.index"
vector_match_threshold: 0.75
relationship_discovery_max_path_length: 5
complex_query_hop_depth: 2

# Retrieval Parameters
semantic_search_top_k: 3 # Number of text chunks to retrieve
entity_info_hop_depth: 1 # How many hops to explore around entities found in chunks

# Graph Explorer Defaults
default_full_graph_node_limit: 100
default_full_graph_edge_limit: 150