services:
  # The main Python FastAPI application
  rag-api:
    build: .
    container_name: rag-api-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - weaviate
      - neo4j
      - redis
    restart: on-failure

  # Weaviate Vector Database
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.1
    container_name: weaviate-container
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure
    environment:
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://transformers-inference:8080'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
    depends_on:
      - transformers-inference

  # Hugging Face Model Container (managed by Weaviate)
  transformers-inference: # Service name updated for clarity
    # Correct image repository 'transformers-inference'
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-mpnet-base-cos-v1
    container_name: transformers-inference-container
    restart: on-failure
    environment:
      # This allows you to switch models via the .env file if you wish
      SENTENCE_TRANSFORMERS_MODEL: ${EMBEDDING_MODEL_REPO:-sentence-transformers/multi-qa-mpnet-base-cos-v1}
      ENABLE_CUDA: '0' # Set to '1' if you have a configured GPU

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.18.0
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    restart: on-failure

  # Redis Caching Service
  redis:
    image: redis:7.2-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: on-failure

volumes:
  weaviate_data:
  neo4j_data:
  redis_data: